source 'https://rubygems.org'

gem 'rails', '3.2.6'

# until spurious security warning disappears
gem 'rack', '< 1.4.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'lti2_tc', :github => 'jtibbetts/lti2_tc'
gem 'lti2_tc', :path => '../lti2_tc'

gem 'sqlite3'

gem 'json'
gem 'json-ld'
gem 'jsonpath'

#gem 'lti2_commons', :github => 'jtibbetts/lti2_commons'
gem 'lti2_commons', :path => '../lti2_commons'

gem "haml", '4.0.4'
gem "haml-rails"
gem "haml-contrib"

gem 'RedCloth'
gem "activeadmin" , :git  =>  'git://github.com/gregbell/active_admin.git'
gem 'lrucache'
gem 'httparty', '~> 0.8.1'
gem 'yaml_db'
gem 'mysql2','0.3.13'
gem 'uuid'
# gem 'haml-contrib'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'
