source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '~> 4.0.0'

gem 'mysql2', '~> 0.3.13'
gem 'sqlite3'

gem 'lti2_tc', :path => '../lti2_tc'
gem 'lti2_commons', :path => '../lti2_commons'

gem 'activeadmin', github: 'gregbell/active_admin'
#Active admin dependencies
gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'rails-4'
gem 'inherited_resources', github: 'josevalim/inherited_resources'

gem 'haml-contrib'
gem 'haml-rails', '~> 0.4'
gem 'httparty', '~> 0.8.1'
gem 'jquery-rails', '~> 3.0.4'
gem 'json', '~> 1.8.0'
gem 'jsonpath', '0.5.1'
gem 'lrucache'
gem 'RedCloth', '~> 4.2.9'
gem 'sass-rails', '~> 4.0.0'
gem 'yaml_db'
gem 'uuid', '~> 2.3.7'

group :development do
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '~> 2.4.0'
  gem 'execjs'
  gem 'therubyracer', '~> 0.12.0'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'ruby-core-docs', '~> 2.0.0'
  gem 'pry'
  gem 'pry-plus'
  gem 'pry-rails'
end
